"""Pydantic models for training plans."""

from pydantic import BaseModel, Field


class Training(BaseModel):
    """Single training day in the week plan."""

    day: str = Field(description="Data treningu w formacie YYYY-MM-DD")
    bodyParts: list[str] = Field(
        description="Lista partii ciała do treningu, np. 'Biceps', 'Chest', 'Quadriceps'"
    )


class WeekPlan(BaseModel):
    """Weekly training plan generated by planner agent."""

    weekStart: str = Field(description="Początek tygodnia w formacie YYYY-MM-DD")
    weekEnd: str = Field(description="Koniec tygodnia w formacie YYYY-MM-DD")
    trainings: list[Training] = Field(description="Lista 3 treningów na tydzień")


class Video(BaseModel):
    """Video with URL and metadata."""

    url: str = Field(description="URL do video")
    angle: str | None = Field(default=None, description="Kąt nagrania, np. 'side', 'front'")


class Exercise(BaseModel):
    """Single exercise with details."""

    name: str = Field(description="Nazwa ćwiczenia po polsku")
    videos: list[Video] = Field(description="Lista video instruktażowych z API")
    repetitions: str = Field(description="Serie x powtórzenia, np. '3 x 12'")
    steps: list[str] = Field(description="Kroki wykonania ćwiczenia po polsku")


class TrainingDay(BaseModel):
    """Complete training day with exercises."""

    day: str = Field(description="Data treningu w formacie YYYY-MM-DD")
    name: str = Field(description="Nazwa treningu, np. 'Plecy i Biceps'")
    timeRequired: int = Field(description="Szacowany czas treningu w minutach")
    exercises: list[Exercise] = Field(description="Lista ćwiczeń na dany dzień")


class FinalPlan(BaseModel):
    """Final training plan with all exercises filled in."""

    trainings: list[TrainingDay] = Field(description="Lista treningów z ćwiczeniami")
